# -*- yaml -*-
# METABUILD GENERATED metaconf/metaconf.groovy + metaconf/project/build.yaml.tmpl -> atlasdb/commons-db/build.yaml
meta:
  name: CommonsDb
  gradle_name: commons-db
  use_legacy_revision: true
  source_target_version: 1.6
  skip_dist: true
jars:
  -
    name: commons-db
    src:
      - src/main/java
