# -*- yaml -*-
# METABUILD GENERATED metaconf/metaconf.groovy + metaconf/project/build.yaml.tmpl -> atlasdb/papaya/build.yaml
meta:
  name: AtlasdbPapaya
  gradle_name: atlasdb-papaya
  use_legacy_revision: true
  source_target_version: 1.6
  skip_dist: true
jars:
  -
    name: atlasdb-papaya
    src:
      - src
  -
    name: atlasdb-papaya-test
    src:
      - test-src
    depends:
      - atlasdb-papaya
    is_test: true
    ivy_conf: test
